FROM jupyterhub/jupyterhub:0.9.3

COPY jupyterhub/jupyterhub_config.py .

# Download script to automatically stop idle single-user servers
# RUN wget https://raw.githubusercontent.com/jupyterhub/jupyterhub/0.9.3/examples/cull-idle/cull_idle_servers.py

# Install dependencies (for advanced authentication and spawning)
RUN pip install \
    dockerspawner==0.10.0 \
    oauthenticator==0.8.0
